### PR TITLE
Added turning functions (center, back, and back corners)

### PR DESCRIPTION
**Pull request by jbajaj6**
Before issuing a pull request, please see the contributing page.

### CODE REVIEW

**Comment by jbajaj6** [comment]
Ok I will do it. Thanks for letting me know.

**Review by JSalenger — CHANGES_REQUESTED** [review]
Functions, `turnViaBackCorners` and `turnViaFrontCorners` provide no way to specify which front/back corner you'd like to use as the center point for your turn. Please fix

**Comment by JSalenger** [comment]
Remove everything that has to do with corners, you're confusing yourself by making this too complicated. Keep turnViaFront, Back, and Center. Then I'll merge and do corners myself.

**Comment by JSalenger** [comment]
Also please update your fork,
[https://levelup.gitconnected.com/how-to-update-fork-repo-from-original-repo-b853387dd471](https://levelup.gitconnected.com/how-to-update-fork-repo-from-original-repo-b853387dd471)

**Comment by JSalenger** [comment]
Everything is probably ok

**Review by JSalenger — APPROVED** [review]

**Pull request merged**
